language: go
env:
  - NODE_VERSION="8.10" GO111MODULE=on

before_install:
  - nvm install $NODE_VERSION
install:
  - go mod download
  - cd vscode-yolol && npm install && npm install -g vsce && cd ..
script:
  - go test ./...
  - go build
  - ./yodk test examples/*_test.yaml
  - GOOS=windows go build
before_deploy:
  - VERSION=$(git describe --tags)
  - zip yodk-win.zip yodk.exe
  - zip yodk-linux.zip yodk
  - cd vscode-yolol && vsce package && cp *.vsix ../vscode-yolol.vsix && cd ..
deploy:
  - provider: releases
    api-key: $GITHUB_TOKEN
    file: 
      - yodk-win.zip
      - yodk-linux.zip
      - vscode-yolol.vsix
    skip_cleanup: true
    on:
        tags: true
  - provider: script
    script: cd vscode-yolol && vsce publish -p ${VSCODE_MARKETPLACE_TOKEN} $(echo ${TRAVIS_TAG} | tr -d v)
    skip_cleanup: true
    on:
      tags: true