language: go
dist: bionic
services:
  - xvfb
env:
  - NODE_VERSION="8.10" GO111MODULE=on

before_install:
  - nvm install $NODE_VERSION
install:
  - go mod download
  - cd vscode-yolol && npm install && npm install -g vsce && cd ..
before_script:
  - export DISPLAY=:99.0;
script:
  - go test ./...
  - go build -ldflags "-X github.com/dbaumgarten/yodk/cmd.YodkVersion=${TRAVIS_BRANCH}"
  - ./yodk version
  - ./yodk test examples/yolol/*_test.yaml
  - ./yodk test examples/nolol/*_test.yaml
  - GOOS=windows go build -ldflags "-X github.com/dbaumgarten/yodk/cmd.YodkVersion=${TRAVIS_BRANCH}"
  - cd vscode-yolol
  - npm run vscode:prepublish
  - npm test --silent
  - cd ..
before_deploy:
  - zip yodk-win.zip yodk.exe
  - zip yodk-linux.zip yodk
  - cd vscode-yolol
  - npm version --no-git-tag-version $(echo ${TRAVIS_TAG} | tr -d v) --allow-same-version
  - vsce package
  - cp *.vsix ../vscode-yolol.vsix
  - cd ..
  - ./build-docs.sh
deploy:
  - provider: releases
    api-key: $GITHUB_TOKEN
    file: 
      - yodk-win.zip
      - yodk-linux.zip
      - vscode-yolol.vsix
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: cd vscode-yolol && vsce publish -p ${VSCODE_MARKETPLACE_TOKEN}
    skip_cleanup: true
    on:
      tags: true
  - provider: pages
    local_dir: docs
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master